//
// Copyright (C) 1993-1996 Id Software, Inc.
// Copyright (C) 2016-2017 Alexey Khokholov (Nuke.YKT)
// Copyright (C) 2017 Alexandre-Xavier Labonte-Lamoureux
// Copyright (C) 2017-2021 Julian Nechaevsky
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// DESCRIPTION:
//  DOOM main program (D_DoomMain) and game loop (D_DoomLoop),
//  plus functions to determine game mode (shareware, registered),
//  parse command line parameters, configure game parameters (turbo),
//  and call the startup functions.
//

#include <stdlib.h>
#include <dos.h>
#include <direct.h>
#include <io.h>

#include "doomdef.h"
#include "doomstat.h"
#include "sounds.h"
#include "z_zone.h"
#include "w_wad.h"
#include "s_sound.h"
#include "v_video.h"
#include "f_finale.h"
#include "f_wipe.h"
#include "m_misc.h"
#include "m_menu.h"
#include "i_system.h"
#include "i_sound.h"
#include "g_game.h"
#include "hu_stuff.h"
#include "wi_stuff.h"
#include "st_stuff.h"
#include "am_map.h"
#include "p_setup.h"
#include "r_local.h"
#include "d_main.h"
#include "m_misc.h"
#include "rd_lang.h"
#include "jn.h"


#define MAXWADFILES     20
#define MAXARGVS        100


//
// D-DoomLoop()
// Not a globally visible function,
//  just included for source reference,
//  called by D_DoomMain, never exits.
// Manages timing and IO,
//  calls all ?_Responder, ?_Ticker, and ?_Drawer,
//  calls I_GetTime, I_StartFrame, and I_StartTic
//
void D_DoomLoop (void);
void D_CheckNetGame (void);
void D_ProcessEvents (void);
void G_BuildTiccmd (ticcmd_t* cmd);
void D_DoAdvanceDemo (void);
void R_ExecuteSetViewSize (void);


char        basedefault[1024];      // default file
char        wadfile[1024];          // primary wad file
char*       wadfiles[MAXWADFILES];

boolean     devparm;                // started game with -devparm
boolean     nomonsters;             // checkparm of -nomonsters
boolean     respawnparm;            // checkparm of -respawn
boolean     fastparm;               // checkparm of -fast
boolean	    singletics = false;     // debug flag to cancel adaptiveness

skill_t     startskill;
int         startepisode;
int         startmap;
boolean     autostart;

FILE*       debugfile;

boolean     advancedemo;
boolean     modifiedgame;

boolean     shareware;
boolean     registered;
boolean     retail;
boolean     commercial;
boolean     plutonia;
boolean     tnt;
boolean     altfinal;
boolean     vanilla;
boolean     sigil;


//
// EVENT HANDLING
//
// Events are asynchronous inputs generally generated by the game user.
// Events can be discarded if no responder claims them
//
event_t     events[MAXEVENTS];
int         eventhead;
int         eventtail;

//
// DEMO LOOP
//
int         demosequence;
int         pagetic;
char       *pagename;

// wipegamestate can be set to -1 to force a wipe on the next draw
gamestate_t wipegamestate = GS_DEMOSCREEN;

// print title for every printed line
char        title[128];

extern boolean  setsizeneeded;

//
// D_PostEvent
// Called by the I/O functions when input is detected
//
void D_PostEvent (event_t *ev)
{
    events[eventhead] = *ev;
    eventhead = (++eventhead)&(MAXEVENTS-1);
}


//
// D_ProcessEvents
// Send all the events of the given timestamp down the responder chain
//
void D_ProcessEvents (void)
{
    event_t *ev;

    for ( ; eventtail != eventhead ; eventtail = (++eventtail)&(MAXEVENTS-1) )
    {
        ev = &events[eventtail];

        if (M_Responder (ev))
        continue; // menu ate the event

        G_Responder (ev);
    }
}


//
// FixedDiv, C version.
//
fixed_t FixedDiv (fixed_t a, fixed_t b)
{
    if ( (abs(a)>>14) >= abs(b))
    return (a^b)<0 ? MININT : MAXINT;
    return FixedDiv2 (a,b);
}


//
// D_Display
//  draw current display, possibly wiping it from the previous
//
void D_Display (void)
{
    int             tics;
    int             wipestart;
    int             y;
    boolean         done;
    boolean         wipe;
    boolean         redrawsbar;
    static int      borderdrawcount;
    static boolean  viewactivestate = false;
    static boolean  menuactivestate = false;
    static boolean  inhelpscreensstate = false;
    static boolean  fullscreen = false;
    static gamestate_t  oldgamestate = -1;

    redrawsbar = false;

    // change the view size if needed
    if (setsizeneeded)
    {
        R_ExecuteSetViewSize();
        oldgamestate = -1; // force background redraw
        borderdrawcount = 3;
    }

    // save the current screen if about to wipe
    if (gamestate != wipegamestate)
    {
        wipe = true;
        wipe_StartScreen(0, 0, SCREENWIDTH, SCREENHEIGHT);
    }
    else
    {
        wipe = false;
    }

    if (gamestate == GS_LEVEL && gametic)
    {
        HU_Erase();
    }

    // do buffered drawing
    switch (gamestate)
    {
        case GS_LEVEL:
        {
            if (!gametic)
            break;

            if (automapactive)
            {
                // [crispy] update automap while playing
                R_RenderPlayerView (&players[displayplayer]);
                AM_Drawer ();
            }

            if (wipe || (viewheight != SCREENHEIGHT && fullscreen))
            {
                redrawsbar = true;
            }

            if (inhelpscreensstate && !inhelpscreens)
            {
                redrawsbar = true; // just put away the help screen
            }

            ST_Drawer (viewheight == SCREENHEIGHT, redrawsbar );
            fullscreen = viewheight == SCREENHEIGHT;

            break;
        }

        case GS_INTERMISSION:
        {
            WI_Drawer ();
            break;
        }

        case GS_FINALE:
        {
            F_Drawer ();
            break;
        }

        case GS_DEMOSCREEN:
        {
            D_PageDrawer ();
            break;
        }
    }

    // draw buffered stuff to screen
    I_UpdateNoBlit ();

    // draw the view directly
    if (gamestate == GS_LEVEL && !automapactive && gametic)
    {
        R_RenderPlayerView (&players[displayplayer]);

        // [JN] Make HUD calculations for active Crispy HUDs
        if (screenblocks >= 11 || screenblocks <= 13)
        ST_Drawer(0, 0);
    }

    if (gamestate == GS_LEVEL && gametic)
    {
        HU_Drawer ();
    }

    // clean up border stuff
    if (gamestate != oldgamestate && gamestate != GS_LEVEL)
    {
        I_SetPalette (W_CacheLumpName (usegamma <= 8 ? 
                      "PALFIX" : "PLAYPAL", PU_CACHE));
    }

    // see if the border needs to be initially drawn
    if (gamestate == GS_LEVEL && oldgamestate != GS_LEVEL)
    {
        viewactivestate = false; // view was not active
        R_FillBackScreen ();     // draw the pattern into the back screen
    }

    // see if the border needs to be updated to the screen
    if (gamestate == GS_LEVEL && !automapactive && scaledviewwidth != SCREENWIDTH)
    {
        if (menuactive || menuactivestate || !viewactivestate)
        {
            borderdrawcount = 3;
        }

        if (borderdrawcount)
        {
            R_DrawViewBorder (); // erase old menu stuff
            borderdrawcount--;
        }
    }

    menuactivestate = menuactive;
    viewactivestate = viewactive;
    inhelpscreensstate = inhelpscreens;
    oldgamestate = wipegamestate = gamestate;

    // [JN] Draw pause pic. Don't draw while actime game menu and help screens.
    if (paused && !menuactive)
    {
        if (automapactive)
        {
            y = 4;
        }
        else if (gamestate == GS_INTERMISSION)
        {
            // [JN] Do not obstruct titles on intermission screen
            y = 32;
        }
        else
        {
            y = viewwindowy+4;
        }

        V_DrawShadowDirect(viewwindowx+(scaledviewwidth-68)/2+1, y+1, 0,
                           W_CacheLumpName (english_language ? "M_PAUSE" :
                                                               "RD_PAUSE", PU_CACHE));
        V_DrawPatchDirect(viewwindowx+(scaledviewwidth-68)/2, y, 0,
                          W_CacheLumpName (english_language ? "M_PAUSE" :
                                                              "RD_PAUSE", PU_CACHE));
    }

    // menus go directly to the screen
    M_Drawer();  // menu is drawn even on top of everything
    NetUpdate(); // send out any new accumulation

    // normal update
    if (!wipe)
    {
        I_FinishUpdate (); // page flip or blit buffer
        return;
    }

    // wipe update
    wipe_EndScreen(0, 0, SCREENWIDTH, SCREENHEIGHT);
    wipestart = I_GetTime () - 1;

    do
    {
        do
        {
            tics = I_GetTime() - wipestart;
        } while (!tics);

        wipestart = I_GetTime();
        done = wipe_ScreenWipe(wipe_Melt, 0, 0, SCREENWIDTH, SCREENHEIGHT, tics);
        I_UpdateNoBlit();
        M_Drawer();       // menu is drawn even on top of wipes
        I_FinishUpdate(); // page flip or blit buffer
    } while (!done);
}


//
// D_DoomLoop
//
void D_DoomLoop (void)
{
    if (demorecording)
    G_BeginRecording ();

    if (M_CheckParm ("-debugfile"))
    {
        char filename[20];

        sprintf (filename,"debug%i.txt",consoleplayer);
        printf (english_language ?
                "debug output to: %s\n" :
                "запись отладочного файла: %s\n", filename);
        debugfile = fopen (filename,"w");
    }

    I_InitGraphics();

    while (1)
    {
        // frame syncronous IO operations		
        I_StartFrame();                		

        // process one or more tics
        if (singletics)
        {
            I_StartTic();
            D_ProcessEvents();
            G_BuildTiccmd (&netcmds[consoleplayer][maketic%BACKUPTICS]);

            if (advancedemo)
            D_DoAdvanceDemo();

            M_Ticker();
            G_Ticker();
            gametic++;
            maketic++;
        }
        else
        {
            TryRunTics(); // will run at least one tic
        }

        S_UpdateSounds (players[consoleplayer].mo);// move positional sounds

        // Update display, next frame, with current state.
        D_Display ();
    }
}


//
// D_PageTicker
// Handles timing for warped projection
//
void D_PageTicker (void)
{
    if (--pagetic < 0)
    {
        D_AdvanceDemo();
    }
}


//
// D_PageDrawer
//
void D_PageDrawer (void)
{
    V_DrawPatch (0, 0, 0, W_CacheLumpName(pagename, PU_CACHE));
}


//
// D_AdvanceDemo
// Called after each demo or intro demosequence finishes
//
void D_AdvanceDemo (void)
{
    advancedemo = true;
}


//
// This cycles through the demo sequences.
// FIXME - version dependend demo numbers?
//
void D_DoAdvanceDemo (void)
{
    players[consoleplayer].playerstate = PST_LIVE; // not reborn
    advancedemo = false;
    usergame = false; // no save / end game here
    paused = false;
    gameaction = ga_nothing;

    if (retail && W_GetNumForName("demo4"))
    demosequence = (demosequence+1)%7;
    else
    demosequence = (demosequence+1)%6;

    switch (demosequence)
    {
        case 0:
        {
            pagetic = commercial ? 385 : 170;
            gamestate = GS_DEMOSCREEN;
            if (english_language)
            {
                pagename = "TITLEPIC";
            }
            else
            {
                pagename = shareware ? "TITLEPIS" :
                            plutonia ? "TITLEPIP" :
                                 tnt ? "TITLEPIT" :
                               sigil ? "TITLESIG" :
                                       "TITLEPIC" ;
            }
            S_StartMusic(commercial ? mus_dm2ttl : mus_intro);
            break;
        }

        case 1:
        {
            if (!no_internal_demos)
            {
                G_DeferedPlayDemo ("demo1");
            }
            break;
        }

        case 2:
        {
            pagetic = 200;
            gamestate = GS_DEMOSCREEN;
            if (english_language)
            {
                pagename = "CREDIT";
            }
            else
            {
                pagename = shareware || registered ? "CREDITS" :
                                             sigil ? "HELPSIG" :
                                            retail ? "CREDITU" :
                                                     "CREDIT2" ;
            }
            break;
        }

        case 3:
        {
            if (!no_internal_demos)
            {
                G_DeferedPlayDemo ("demo2");
            }
            break;
        }

        case 4:
        {
            gamestate = GS_DEMOSCREEN;
            if (commercial)
            {
                pagetic = 385;
                if (english_language)
                {
                    pagename = "TITLEPIC";
                }
                else
                {
                    pagename = plutonia ? "TITLEPIP" :
                                    tnt ? "TITLEPIT" :
                                  sigil ? "TITLESIG" :
                                          "TITLEPIC" ;
                }
    
                S_StartMusic(mus_dm2ttl);
            }
            else
            {
                pagetic = 200;
    
                if (english_language)
                {
                    pagename = retail ? "CREDIT" :
                                        "HELP2"  ;
                }
                else
                {
                    pagename = sigil ? "HELPSIG" :
                              retail ? "CREDITU" :
                                       "HELP2R"  ;
                }
            }
            break;
        }

        case 5:
        {
            if (!no_internal_demos)
            {
                G_DeferedPlayDemo ("demo3");
            }
            break;
        }

        case 6: // THE DEFINITIVE DOOM Special Edition demo
        {
            if (!no_internal_demos)
            {
                G_DeferedPlayDemo ("demo4");
            }
            break;
        }
    }

    // The Doom 3: BFG Edition version of doom2.wad does not have a
    // TITLETPIC lump. Use INTERPIC instead as a workaround.
    if (!strcasecmp(pagename, "TITLEPIC") && W_GetNumForName("titlepic") < 0)
    {
        // [crispy] use DMENUPIC instead of TITLEPIC, it's awesome
        pagename = "DMENUPIC";
    }
}


//
// D_StartTitle
//
void D_StartTitle (void)
{
    gameaction = ga_nothing;
    demosequence = -1;
    D_AdvanceDemo ();
}


//
// D_GetCursorColumn
//
int D_GetCursorColumn(void)
{
    union REGS regs;

    regs.h.ah = 3;
    regs.h.bh = 0;
    int386(0x10, &regs, &regs);

    return regs.h.dl;
}


//
// D_GetCursorRow
//
int D_GetCursorRow(void)
{
    union REGS regs;

    regs.h.ah = 3;
    regs.h.bh = 0;
    int386(0x10, &regs, &regs);

    return regs.h.dh;
}


//
// D_SetCursorPosition
//
void D_SetCursorPosition(int column, int row)
{
    union REGS regs;

    regs.h.dh = row;
    regs.h.dl = column;
    regs.h.ah = 2;
    regs.h.bh = 0;
    int386(0x10, &regs, &regs);
}


//
// D_DrawTitle
//
void D_DrawTitle(char *string, int fc, int bc)
{
    int   column;
    int   row;
    int   i;
    byte  color;
    union REGS regs;

    //Calculate text color
    color = (bc << 4) | fc;

    //Get column position
    column = D_GetCursorColumn();

    //Get row position
    row = D_GetCursorRow();

    for (i = 0; i < strlen(string); i++)
    {
        //Set character
        regs.h.ah = 9;
        regs.h.al = string[i];
        regs.w.cx = 1;
        regs.h.bl = color;
        regs.h.bh = 0;
        int386(0x10, &regs, &regs);

        //Check cursor position
        if (++column > 79)
        column = 0;

        //Set position
        D_SetCursorPosition(column, row);
    }
}


//
// D_RedrawTitle
//
void D_RedrawTitle(void)
{
    int column;
    int row;

    //Get current cursor pos
    column = D_GetCursorColumn();
    row = D_GetCursorRow();

    //Set cursor pos to zero
    D_SetCursorPosition(0, 0);

    // [JN] Different title colors for different games
    // http://www.brackeen.com/vga/basics.html

    if (vanilla)
    {
        if (retail || tnt || plutonia)
        D_DrawTitle(title, 8, 7);
        else // (shareware || registered || commercial)
        D_DrawTitle(title, 4, 7);
    }
    else
    {
        if (shareware)
        D_DrawTitle(title, 14, 1);
        else if (registered)
        D_DrawTitle(title, 15, 1);
        else if (retail)
        D_DrawTitle(title, 15, 6);
        else if (tnt)
        D_DrawTitle(title, 14, 4);
        else if (plutonia)
        D_DrawTitle(title, 15, 2);
        else
        D_DrawTitle(title, 15, 4);
    }

    //Restore old cursor pos
    D_SetCursorPosition(column, row);
}


//
// D_AddFile
//
void D_AddFile (char *file)
{
    int    numwadfiles;
    char  *newfile;

    for (numwadfiles = 0 ; wadfiles[numwadfiles] ; numwadfiles++)
    ;

    newfile = malloc (strlen(file)+1);
    strcpy (newfile, file);

    wadfiles[numwadfiles] = newfile;
}


//
// IdentifyVersion
// Checks availability of IWAD files by name,
// to determine whether registered/commercial features
// should be executed (notably loading PWAD's).
//
void IdentifyVersion (void)
{
    int p;

    // [JN] Moderate purism's Vanilla gameplay mode
    if (M_CheckParm ("-vanilla"))
    vanilla = true;

    strcpy(basedefault,"default.cfg");
    
    if (M_CheckParm ("-alt"))
    altfinal = true;

    // [JN] -IWAD loading
    p = M_CheckParm ("-iwad");
    if (p && p < myargc-1)
    {
        if( !access (myargv[p+1],R_OK) )
        {

            if ( !strcasecmp (myargv[p+1],"doom2.wad") )
            {
                commercial = true;
                D_AddFile ("doom2.wad");
                return;
            }

            if ( !strcasecmp (myargv[p+1],"plutonia.wad") )
            {
                commercial = true;
                plutonia = true;
                D_AddFile ("plutonia.wad");
                return;
            }

            if ( !strcasecmp (myargv[p+1],"tnt.wad") )
            {
                commercial = true;
                tnt = true;
                D_AddFile ("tnt.wad");
                return;
            }

            if ( !strcasecmp (myargv[p+1],"doom.wad") )
            {
                registered = true;
                D_AddFile ("doom.wad");
                return;
            }

            if ( !strcasecmp (myargv[p+1],"doom1.wad") )
            {
                shareware = true;
                D_AddFile ("doom1.wad");
                return;
            }
        }
    }
    else
    {
        if ( !access ("doom2.wad",R_OK) )
        {
            commercial = true;
            D_AddFile ("doom2.wad");
            return;
        }

        if ( !access ("plutonia.wad",R_OK) )
        {
            commercial = true;
            plutonia = true;
            D_AddFile ("plutonia.wad");
            return;
        }

        if ( !access ( "tnt.wad",R_OK) )
        {
            commercial = true;
            tnt = true;
            D_AddFile ("tnt.wad");
            return;
        }

        if ( !access ("doom.wad",R_OK) )
        {
            registered = true;
            D_AddFile ("doom.wad");
            return;
        }

        if ( !access ("doom1.wad",R_OK) )
        {
            shareware = true;
            D_AddFile ("doom1.wad");
            return;
        }
    }

    printf(english_language ?
           "Game mode indeterminate\n" :
           "Невозможно определить игру.\n");
    exit(1);
}


//
// Find a Response File
//
void FindResponseFile (void)
{
    int i;

    for (i = 1 ; i < myargc ; i++)
    if (myargv[i][0] == '@')
    {
        FILE  *handle;
        int    size;
        int    k;
        int    index;
        int    indexinfile;
        char  *infile;
        char  *file;
        char  *moreargs[20];
        char  *firstargv;

        // READ THE RESPONSE FILE INTO MEMORY
        handle = fopen (&myargv[i][1],"rb");

        if (!handle)
        {
            printf (english_language ?
                    "\nNo such response file!" :
                    "\nОтсутствует ответный файл!");
            exit(1);
        }

        printf(english_language ?
               "Found response file %s!\n" :
               "Найден ответный файл %s!\n", &myargv[i][1]);
        fseek (handle,0,SEEK_END);
        size = ftell(handle);
        fseek (handle,0,SEEK_SET);
        file = malloc (size);
        fread (file,size,1,handle);
        fclose (handle);

        // KEEP ALL CMDLINE ARGS FOLLOWING @RESPONSEFILE ARG
        for (index = 0, k = i+1 ; k < myargc ; k++)
        moreargs[index++] = myargv[k];

        firstargv = myargv[0];
        myargv = malloc(sizeof(char *)*MAXARGVS);
        memset(myargv,0,sizeof(char *)*MAXARGVS);
        myargv[0] = firstargv;

        infile = file;
        indexinfile = k = 0;
        indexinfile++; // SKIP PAST ARGV[0] (KEEP IT)

        do
        {
            myargv[indexinfile++] = infile+k;
            while(k < size && ((*(infile+k)>= ' '+1) && (*(infile+k)<='z')))
            k++;
            *(infile+k) = 0;
            while(k < size && ((*(infile+k)<= ' ') || (*(infile+k)>'z')))
            k++;
        } while(k < size);

        for (k = 0 ; k < index ; k++)
        myargv[indexinfile++] = moreargs[k];
        myargc = indexinfile;

        // DISPLAY ARGS
        printf(english_language ?
               "%d command-line args:\n" :
               "%d параметры командной строки:\n", myargc);

        for (k=1 ; k < myargc ; k++)
        printf("%s\n",myargv[k]);

        break;
    }
}


//
// D_DoomMain
//
void D_DoomMain (void)
{
    int     p;
    char    file[256];
    union   REGS regs;

    FindResponseFile();

    IdentifyVersion ();

    setbuf(stdout, NULL);
    modifiedgame = false;

    nomonsters = M_CheckParm("-nomonsters");
    respawnparm = M_CheckParm("-respawn");
    fastparm = M_CheckParm("-fast");
    devparm = M_CheckParm("-devparm");

    if (M_CheckParm("-dm3"))
    deathmatch = 3;
    else if (M_CheckParm("-altdeath"))
    deathmatch = 2;
    else if (M_CheckParm("-deathmatch"))
    deathmatch = 1;

    // [JN] Load variables first, so we can show 
    // startup string with proper language.
    printf(english_language ? 
           "M_LoadDefaults: Load system defaults.\n" :
           "M_LoadDefaults: Загрузка системных стандартов.\n");
    M_LoadDefaults();

    // [JN] Load Russian Doom resource PWAD.
    D_AddFile ("rusdoom.wad");

    // [JN] Define and load translated strings
    RD_DefineLanguageStrings();

    if (shareware || registered)
    {
        if (english_language)
        {
            sprintf(title,
            "                            "
            "DOOM System Startup v%i.%i"
            "                            ",
            VERSION/100,VERSION%100);
        }
        else
        {
            sprintf(title,
            "                           "
            "Система загрузки DOOM v%i.%i"
            "                           ",
            VERSION/100,VERSION%100);
        }
    }
    else if (retail)
    {
        sprintf(title,
        "                             "
        "The Ultimate DOOM v%i.%i"
        "                             ",
        VERSION/100,VERSION%100);
    }
    else if (tnt)
    {
        if (english_language)
        {
            sprintf(title,
            "                        "
            "Final DOOM: TNT - Evilution v%i.%i"
            "                        ",
            VERSION/100,VERSION%100);
        }
        else
        {
            sprintf(title,
            "                       "
            "Final DOOM: TNT - Дьяволюция v%i.%i"
            "                        ",
            VERSION/100,VERSION%100);
        }
    }
    else if (plutonia)
    {
        if (english_language)
        {
            sprintf(title,
            "                      "
            "Final DOOM: Plutonia Experiment v%i.%i"
            "                      ",
            VERSION/100,VERSION%100);
        }
        else
        {
            sprintf(title,
            "                    "
            "Final DOOM: Эксперимент \"Плутония\" v%i.%i"
            "                     ",
            VERSION/100,VERSION%100);
        }
    }
    else if (commercial)
    {
        if (english_language)
        {
            sprintf(title,
            "                          "
            "DOOM 2: Hell on Earth v%i.%i"
            "                            ",
            VERSION/100,VERSION%100);
        }
        else
        {
            sprintf(title,
            "                            "
            "DOOM 2: Ад на Земле v%i.%i"
            "                            ",
            VERSION/100,VERSION%100);
        }
    }

    regs.w.ax = 3;
    int386(0x10, &regs, &regs);
    // [JN] Colors are:
    // 15 - foreground, white color
    //  0 - background, black color
    D_DrawTitle(title, 15, 0);

    printf(english_language ?
    "\nP_Init: Checking cmd-line parameters...\n" :
    "\nP_Init: Проверка параметров командной строки...\n");

    if (devparm)
    {
        printf(english_language ? D_DEVSTR : D_DEVSTR_RUS);
        D_RedrawTitle();
    }

    if (M_CheckParm("-cdrom"))
    {
        printf(english_language ? D_CDROM : D_CDROM_RUS);
        mkdir("c:\\doomdata");
        strcpy (basedefault,"c:/doomdata/default.cfg");
    }	

    // turbo option
    if ( (p=M_CheckParm ("-turbo")) )
    {
        int         scale = 200;
        extern int  forwardmove[2];
        extern int  sidemove[2];

        if (p<myargc-1)
        scale = atoi (myargv[p+1]);
        if (scale < 10)
        scale = 10;
        if (scale > 400)
        scale = 400;

        printf (english_language ?
                "turbo scale: %i%%\n" :
                "турбо ускорение: %i%%\n",scale);
        forwardmove[0] = forwardmove[0]*scale/100;
        forwardmove[1] = forwardmove[1]*scale/100;
        sidemove[0] = sidemove[0]*scale/100;
        sidemove[1] = sidemove[1]*scale/100;
    }

    // add any files specified on the command line with -file wadfile
    // to the wad list
    p = M_CheckParm ("-file");
    if (p)
    {
        // the parms after p are wadfile/lump names,
        // until end of parms or another - preceded parm
        modifiedgame = true; // homebrew levels
        while (++p != myargc && myargv[p][0] != '-')
	    D_AddFile (myargv[p]);
    }

    p = M_CheckParm ("-playdemo");

    if (!p)
    p = M_CheckParm ("-timedemo");

    if (p && p < myargc-1)
    {
        sprintf (file,"%s.lmp", myargv[p+1]);
        D_AddFile (file);
        printf(english_language ?
               "Playing demo %s.lmp.\n" :
               "Проигрывание демозаписи %s.lmp.\n", myargv[p+1]);
    }

    // get skill / episode / map from parms
    startskill = sk_medium;
    startepisode = 1;
    startmap = 1;
    autostart = false;

    p = M_CheckParm ("-skill");
    if (p && p < myargc-1)
    {
        startskill = myargv[p+1][0]-'1';
        autostart = true;
    }

    p = M_CheckParm ("-episode");
    if (p && p < myargc-1)
    {
        startepisode = myargv[p+1][0]-'0';
        startmap = 1;
        autostart = true;
    }

    p = M_CheckParm ("-timer");
    if (p && p < myargc-1 && deathmatch)
    {
        int time;

        time = atoi(myargv[p+1]);
        printf(english_language ?
               "Levels will end after %d minute" :
               "Уровни будут завершаться после %d минут(ы)", time);

        if (time>1)
        printf("s");
        printf(".\n");
    }

    p = M_CheckParm ("-avg");
    if (p && p < myargc-1 && deathmatch)
    printf(english_language ?
           "Austin Virtual Gaming: Levels will end after 20 minutes\n" :
           "Austin Virtual Gaming: Уровни будут завершаться после 20 минут\n");

    p = M_CheckParm ("-warp");
    if (p && p < myargc-1)
    {
        if (commercial)
        startmap = atoi (myargv[p+1]);
        else
        {
            startepisode = myargv[p+1][0]-'0';
            startmap = myargv[p+2][0]-'0';
        }

        autostart = true;
    }

    // init subsystems
    printf(english_language ? 
           "V_Init: Allocate screens.\n" :
           "V_Init: Обнаружение экранов.\n");
    V_Init();

    printf(english_language ?
           "Z_Init: Init zone memory allocation daemon. \n" :
           "Z_Init: Инициализация распределения памяти. \n");
    Z_Init();

    printf (english_language ?
            "W_Init: Init WADfiles.\n" :
            "W_Init: Инициализация WAD-файлов.\n");
    W_InitMultipleFiles (wadfiles);

    if (W_GetNumForName("E4M1") >= 0)
    {
        registered = false;
        retail = true;

        if (english_language)
        {
            sprintf(title,
            "                         "
            "The Ultimate DOOM Startup v%i.%i"
            "                         ",
            VERSION/100,VERSION%100);
        }
        else
        {
            sprintf(title,
            "                          "
            "Загрузка Ultimate DOOM v%i.%i"
            "                           ",
            VERSION/100,VERSION%100);
        }
        D_RedrawTitle();
    }

    // [JN] Check for SIGIL loading.
    // Only main version with five episodes is supported.
    p = M_CheckParmWithArgs ("-file", 1);
    if (p)
    {
        while (++p != myargc && myargv[p][0] != '-')
        {
            boolean check = 
               M_StrCaseStr(myargv[p], "SIGIL_~1.wad")
            || M_StrCaseStr(myargv[p], "SIGIL.wad")
            || M_StrCaseStr(myargv[p], "SIGIL_v1_2.wad")
            || M_StrCaseStr(myargv[p], "SIGIL_v1_21.wad");

            if (check)
            {
                sigil = true;
            }
        }
    }

    // Check for -file in shareware
    if (modifiedgame || !commercial)
    {
        // These are the lumps that will be checked in IWAD,
        // if any one is not present, execution will be aborted.
        char name[23][8]=
        {
            "e2m1","e2m2","e2m3","e2m4","e2m5","e2m6","e2m7","e2m8","e2m9",
            "e3m1","e3m3","e3m3","e3m4","e3m5","e3m6","e3m7","e3m8","e3m9",
            "dphoof","bfgga0","heada1","cybra1","spida1d1"
        };

        int i;

        // Check for fake IWAD with right name,
        // but w/o all the lumps of the registered version. 
        if (registered)
        for (i = 0;i < 23; i++)
        if (W_GetNumForName(name[i])<0)
        {
            shareware = true;
            retail = registered = false;
        }
    }

    // Check and print which version is executed.

    if (registered)
    {
        if (retail)
        printf(english_language ? 
               "\tretail version.\n" :
               "\tкоммерческая версия.\n");
        else
        printf(english_language ? 
               "\tregistered version.\n" :
               "\tзарегистрированная версия.\n");

        D_RedrawTitle();
        if (english_language)
        {
            printf(
            "================================================================================"
            "               This version is NOT SHAREWARE, do not distribute!                "
            "            Please report software piracy to the SPA: 1-800-388-PIR8            "
            "================================================================================"
            );
        }
        else
        {
            printf(
            "================================================================================"
            "          Это не демонстрационная версия игры, не распространяйте ее!           "
            "  Просим вас сообщать о случаях компьютерного пиратства в SPA: 1-800-388-PIR8   "
            "================================================================================"
            );            
        }

        D_RedrawTitle();
    }
    if (shareware)
    {
        printf(english_language ?
               "\tshareware version.\n" :
               "\tдемонстрационная версия.\n");
        D_RedrawTitle();
    }
    if (commercial)
    {
        printf(english_language ?
               "\tcommercial version.\n" :
               "\tкоммерческая версия.\n");
        D_RedrawTitle();
        if (english_language)
        {
            printf(
            "================================================================================"
            "                               Do not distribute!                               "
            "            Please report software piracy to the SPA: 1-800-388-PIR8            "
            "================================================================================"
            );
        }
        else
        {
            printf(
            "================================================================================"
            "          Это не демонстрационная версия игры, не распространяйте ее!           "
            "  Просим вас сообщать о случаях компьютерного пиратства в SPA: 1-800-388-PIR8   "
            "================================================================================"
            );
        }

        D_RedrawTitle();
    }

    printf(english_language ?
           "M_Init: Init miscellaneous info.\n" :
           "M_Init: Инициализация внутренних данных.\n");
    D_RedrawTitle();
    M_Init();

    printf(english_language ?
           "R_Init: Init DOOM refresh daemon - " :
           "R_Init: Инициализация запуска DOOM - ");
    D_RedrawTitle();
    R_Init();

    printf(english_language ?
           "\nP_Init: Init Playloop state.\n" :
           "\nP_Init: Инициализация игрового окружения.\n");
    D_RedrawTitle();
    P_Init();

    printf(english_language ?
           "I_Init: Setting up machine state.\n" :
           "I_Init: Инициализация состояния компьютера.\n");
    D_RedrawTitle();
    I_Init();

    printf(english_language ?
           "D_CheckNetGame: Checking network game status.\n" :
           "D_CheckNetGame: Проверка статуса сетевой игры.\n");
    D_RedrawTitle();
    D_CheckNetGame();

    printf(english_language ?
           "S_Init: Setting up sound.\n" :
           "S_Init: Активация звуковой системы.\n");
    D_RedrawTitle();
    S_Init(sfxVolume*8, musicVolume*8);

    printf(english_language ?
           "HU_Init: Setting up heads up display.\n" :
           "HU_Init: Настройка игрового дисплея.\n");
    D_RedrawTitle();
    HU_Init();

    printf(english_language ?
           "ST_Init: Init status bar.\n" :
           "ST_Init: Инициализация строки состояния.\n");
    D_RedrawTitle();
    ST_Init();

    // check for a driver that wants intermission stats
    p = M_CheckParm ("-statcopy");
    if (p && p<myargc-1)
    {
        // for statistics driver
        extern void*    statcopy;                            

        statcopy = (void*)atoi(myargv[p+1]);
        printf (english_language ?
                "External statistics registered.\n" :
                "Зарегистрирована внешняя статистика.\n");

        D_RedrawTitle();
    }

    // start the apropriate game based on parms
    p = M_CheckParm ("-record");
    if (p && p < myargc-1)
    {
        G_RecordDemo(myargv[p+1]);
        autostart = true;
    }

    p = M_CheckParm ("-playdemo");
    if (p && p < myargc-1)
    {
        singledemo = true; // quit after one demo
        G_DeferedPlayDemo (myargv[p+1]);
        D_DoomLoop(); // never returns
    }

    p = M_CheckParm ("-timedemo");
    if (p && p < myargc-1)
    {
        G_TimeDemo(myargv[p+1]);
        D_DoomLoop(); // never returns
    }

    p = M_CheckParm ("-loadgame");
    if (p && p < myargc-1)
    {
        if (M_CheckParm("-cdrom"))
        sprintf(file, "c:\\doomdata\\"SAVEGAMENAME"%c.sav",myargv[p+1][0]);
        else
        sprintf(file, SAVEGAMENAME"%c.sav",myargv[p+1][0]);

        G_LoadGame(file);
    }

    if ( gameaction != ga_loadgame )
    {
        if (autostart || netgame)
        G_InitNew(startskill, startepisode, startmap);
        else
        D_StartTitle(); // start up intro loop
    }

    D_DoomLoop(); // never returns
}

