//
// Copyright(C) 2013-2018 Brad Harding
// Copyright(C) 2021 Julian Nechaevsky
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// DESCRIPTION:
//	Verious level-specific fixes.
//
//  Note: The idea and the code has been taken from DOOM Retro.
//  Many thanks to Brad Harding for approval of using his work! 
//


#include "d_mode.h"
#include "doomdata.h"
#include "p_fix.h"


vertexfix_t vertexfix[] =
{
    // mission, episode, map, vertex,  oldx,  oldy,  newx,  newy
//  [JN] Nothing for now. An example:
//  {  heretic,       1,   3,    771,  -328, -1920,  -320, -1920 },
    {        0,       0,   0,      0,     0,     0,     0,     0 }
};

linefix_t linefix[] =
{
    // mission, episode, map, linedef, side,  toptexture, middletexture, bottomtexture,  offset, rowoffset,            flags, special,     tag
    {  heretic,       1,   2,     477,    1,  "MOSSRCK1",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       1,   2,     478,    1,  "MOSSRCK1",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       1,   2,     479,    1,  "MOSSRCK1",            "",            "",      96,   DEFAULT,    ML_DONTPEGTOP, DEFAULT, DEFAULT },
    {  heretic,       1,   2,    1057,    0,  "MOSSRCK1",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       1,   3,      21,    1,    "SQPEB1",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       1,   3,      22,    1,    "SQPEB1",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       1,   3,      23,    1,    "SQPEB1",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       1,   3,      24,    1,    "SQPEB1",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       1,   4,     368,    1,  "CTYSTUC4",            "",            "", DEFAULT,        -4,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       1,   4,     473,    1,          "",            "",    "WATRWAL1", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       1,   4,     474,    1,  "CTYSTUC4",            "",            "", DEFAULT,        -4,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       1,   4,     490,    1,          "",            "",     "GRSTNPB", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       1,   4,     722,    0,          "",            "",      "WOODWL", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       1,   4,     911,    0,          "",            "",      "WOODWL", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       1,   4,     913,    0,          "",            "",      "SQPEB1", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       1,   4,     914,    0,          "",            "",      "SQPEB1", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       1,   4,    1296,    0,          "",            "",      "WOODWL", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       1,   5,     519,    0,          "",            "",      "WOODWL", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       1,   5,    1330,    0,   "CSTLRCK",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       1,   5,    1844,    0,          "",            "",    "WATRWAL1", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       1,   5,    1845,    0,          "",            "",    "WATRWAL1", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       1,   6,     491,    1,    "SPINE2",            "",            "", DEFAULT,        -1,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       1,   6,     492,    1,    "SPINE2",            "",            "", DEFAULT,        -1,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       1,   6,     493,    1,    "SPINE2",            "",            "", DEFAULT,        -1,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       1,   6,     494,    1,    "SPINE2",            "",            "", DEFAULT,        -1,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       1,   6,     495,    1,    "SPINE2",            "",            "", DEFAULT,        -1,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       1,   6,    1207,    1,          "",            "",    "SNDBLCKS", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       1,   7,     547,    1,          "",            "",      "SPINE2", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       2,   3,    1029,    1,          "",            "",       "LAVA1", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       2,   5,     486,    1,   "CHAINSD",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       2,   5,     492,    1,   "CHAINSD",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       2,   5,     501,    1,   "CHAINSD",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       2,   5,     507,    1,   "CHAINSD",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       2,   5,     513,    1,   "CHAINSD",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       2,   5,     523,    1,   "CHAINSD",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       2,   5,     528,    1,   "CHAINSD",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       2,   5,     557,    0,   "GRSTNPB",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       2,   5,    1029,    1,   "CHAINSD",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       2,   6,     238,    1,  "TRISTON1",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       2,   6,     726,    0,  "TRISTON1",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       2,   6,     737,    0,  "TRISTON1",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       2,   6,     862,    1,          "",            "",    "TRISTON2", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       2,   7,     493,    1,          "",            "",      "SQPEB1", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       2,   7,     504,    1,          "",            "",      "SQPEB1", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       2,   7,     505,    1,          "",            "",      "SQPEB1", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       2,   7,     506,    1,          "",            "",      "SQPEB1", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       2,   7,     507,    1,          "",            "",      "SQPEB1", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       2,   7,     629,    1,  "LOOSERCK",            "",            "",      16,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       2,   7,     749,    0,          "",            "",       "METL1",     -32,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       3,   1,     295,    0,    "SQPEB1",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       3,   2,     521,    1,  "TRISTON2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       3,   2,     522,    1,  "TRISTON2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       3,   2,     523,    1,  "TRISTON2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       3,   2,     524,    1,  "TRISTON2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       3,   2,     525,    1,  "TRISTON2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       3,   2,     526,    1,  "TRISTON2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       3,   2,     527,    1,  "TRISTON2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       3,   2,     528,    1,  "TRISTON2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       3,   2,     674,    1,          "",            "",       "METL2", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       3,   4,      36,    0,  "SNDPLAIN",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       3,   4,      36,    1,          "",            "",    "SNDPLAIN", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       3,   6,     343,    0,  "MOSSRCK1",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       3,   6,     370,    0,  "MOSSRCK1",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       3,   7,      84,    0,  "MOSSRCK1",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       3,   7,      89,    0,  "MOSSRCK1",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       3,   7,     143,    0,  "MOSSRCK1",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       3,   7,     154,    0,  "MOSSRCK1",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       3,   7,     155,    0,  "MOSSRCK1",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       3,   7,     156,    0,  "MOSSRCK1",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       3,   7,     157,    0,  "MOSSRCK1",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       3,   7,     158,    0,  "MOSSRCK1",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       3,   7,     159,    0,  "MOSSRCK1",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       3,   7,     160,    0,  "MOSSRCK1",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   1,     514,    1,  "SNDCHNKS",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   1,     520,    1,  "SNDCHNKS",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   1,     526,    1,  "SNDCHNKS",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   1,     527,    1,  "SNDCHNKS",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   1,     528,    1,  "SNDCHNKS",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   1,     529,    1,  "SNDCHNKS",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   1,     530,    1,  "SNDCHNKS",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   1,     532,    1,  "SNDCHNKS",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   1,     533,    1,  "SNDCHNKS",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   1,     534,    1,  "SNDCHNKS",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   1,     535,    1,  "SNDCHNKS",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   1,     564,    1,  "SNDCHNKS",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   1,     565,    1,  "SNDCHNKS",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   1,     566,    1,  "SNDCHNKS",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   1,     567,    1,  "SNDCHNKS",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   1,     568,    1,  "SNDCHNKS",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   1,     569,    1,  "SNDCHNKS",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   1,     570,    1,  "SNDCHNKS",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   1,     748,    1,   "CHAINSD",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   1,     765,    0,   "SANDSQ2",            "",            "",       8,         2,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   1,     766,    0,   "SANDSQ2",            "",            "",       8,         2,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   1,     767,    0,   "SANDSQ2",            "",            "", DEFAULT,         2,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   4,     524,    1,          "",            "",       "METL2", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   4,     534,    1,          "",            "",       "METL2", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   4,     544,    1,          "",            "",       "METL2", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   4,     554,    1,          "",            "",       "METL2", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   4,     805,    1,          "",            "",       "METL2", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   4,     808,    0,          "",            "",    "SNDBLCKS", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   4,     963,    1,          "",            "",      "SQPEB1", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   6,     948,    1,          "",            "",    "GRSKULL1", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   7,     721,    1,          "",            "",    "LOOSERCK", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   7,    1274,    1,   "CSTLRCK",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   7,    1277,    1,   "CSTLRCK",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   7,    1278,    1,   "CSTLRCK",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       4,   8,     142,    0,          "",            "",            "", DEFAULT,   DEFAULT,    ML_DONTPEGTOP, DEFAULT, DEFAULT },
    {  heretic,       4,   8,     143,    0,          "",            "",            "", DEFAULT,   DEFAULT,    ML_DONTPEGTOP, DEFAULT, DEFAULT },
    {  heretic,       4,   8,     384,    0,          "",            "",            "", DEFAULT,   DEFAULT,    ML_DONTPEGTOP, DEFAULT, DEFAULT },
    {  heretic,       4,   8,     411,    0,          "",            "",            "", DEFAULT,   DEFAULT,    ML_DONTPEGTOP, DEFAULT, DEFAULT },
    {  heretic,       5,   2,     377,    0,    "SQPEB2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   3,     485,    1,   "CSTLRCK",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   3,     486,    1,   "CSTLRCK",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   3,     487,    1,   "CSTLRCK",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   3,     488,    1,   "CSTLRCK",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   3,     489,    1,   "CSTLRCK",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   3,     492,    1,   "CSTLRCK",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   3,     493,    1,   "CSTLRCK",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   3,     494,    1,   "CSTLRCK",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   3,     497,    1,   "CSTLRCK",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   3,     498,    1,   "CSTLRCK",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   3,     499,    1,   "CSTLRCK",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   3,     500,    1,   "CSTLRCK",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   3,     501,    1,   "CSTLRCK",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   3,     897,    1,   "CSTLRCK",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   4,    1341,    0,  "BLUEFRAG",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   5,     797,    1,          "",            "",       "METL2", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   5,     805,    1,          "",            "",       "METL2", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   5,    1533,    1,    "SPINE2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   5,    1534,    1,    "SPINE2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   5,    1535,    1,    "SPINE2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   5,    1636,    1,          "",            "",       "METL2", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   5,    1642,    1,          "",            "",       "METL2", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   6,     680,    0,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   6,     681,    0,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   6,     682,    0,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   6,     683,    0,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   6,     684,    0,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   6,     685,    0,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   6,    1629,    1,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   6,    1942,    1,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   6,    1945,    1,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   7,    1109,    0,  "CTYSTCI4",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   7,    1337,    1,          "",            "",    "WATRWAL1", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   7,    1338,    1,          "",            "",    "WATRWAL1", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   7,    1339,    1,          "",            "",    "WATRWAL1", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   7,    1340,    1,          "",            "",    "WATRWAL1", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   7,    1344,    1,          "",            "",    "WATRWAL1", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   7,    1345,    1,          "",            "",    "WATRWAL1", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   7,    1348,    1,          "",            "",    "WATRWAL1", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   7,    1349,    1,          "",            "",    "WATRWAL1", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   9,       5,    0,          "",            "",            "",     -32,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   9,      18,    0,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   9,      35,    0,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   9,    1362,    0,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   9,    1363,    0,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   9,    1364,    0,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   9,    1365,    0,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   9,    1366,    0,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   9,    1367,    0,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   9,    1368,    0,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   9,    1369,    0,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   9,    1370,    0,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   9,    1371,    0,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   9,    1372,    0,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   9,    1373,    0,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   9,    1374,    0,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   9,    1375,    0,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   9,    1376,    0,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },
    {  heretic,       5,   9,    1377,    0,     "METL2",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT },

    {        0,       0,   0,       0,    0,          "",            "",            "", DEFAULT,   DEFAULT,          DEFAULT, DEFAULT, DEFAULT }
};

sectorfix_t sectorfix[] =
{
    // mission, episode, map, sector,     floorpic, ceilingpic, floorheight, ceilingheight, special,   oldtag,    newtag
    {  heretic,       1,   5,     49,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     380,  DEFAULT,   DEFAULT },
    {  heretic,       1,   5,     54,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     380,  DEFAULT,   DEFAULT },
    {  heretic,       1,   5,     57,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     380,  DEFAULT,   DEFAULT },    
    {  heretic,       1,   5,     63,   "WATSCRE1",         "",     DEFAULT,       DEFAULT,     230,  DEFAULT,   DEFAULT },
    {  heretic,       1,   5,     86,   "WATSCRE1",         "",     DEFAULT,       DEFAULT,     230,  DEFAULT,   DEFAULT },
    {  heretic,       1,   5,     87,   "WATSCRE1",         "",     DEFAULT,       DEFAULT,     230,  DEFAULT,   DEFAULT },
    {  heretic,       1,   5,     72,   "WATSCRX1",         "",     DEFAULT,       DEFAULT,     330,  DEFAULT,   DEFAULT },
    {  heretic,       1,   5,    295,   "WATSCRX1",         "",     DEFAULT,       DEFAULT,     330,  DEFAULT,   DEFAULT },
    {  heretic,       1,   8,      0,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       1,   8,     35,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       1,   8,     41,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   1,     23,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   1,     28,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   1,     30,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   1,     32,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   2,     95,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   2,    103,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   2,    104,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   2,    106,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   2,    108,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   2,    108,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   2,    114,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   2,    115,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   3,     16,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   3,     19,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   3,     26,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   3,     29,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   3,     53,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   3,     61,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   3,     63,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   3,     80,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   3,     82,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   3,     85,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   3,     87,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   3,    115,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   4,     33,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   4,     79,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,      0,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,      3,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,     11,   "WATSCRS1",         "",     DEFAULT,       DEFAULT,     330,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,     12,   "WATSCRS1",         "",     DEFAULT,       DEFAULT,     330,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,     15,   "WATSCRS1",         "",     DEFAULT,       DEFAULT,     330,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,     16,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     360,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,     19,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     360,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,     21,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     360,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,     24,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     380,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,     52,   "WATSCRS1",         "",     DEFAULT,       DEFAULT,     330,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,     57,   "WATSCRS1",         "",     DEFAULT,       DEFAULT,     330,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,     58,   "WATSCRS1",         "",     DEFAULT,       DEFAULT,     330,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,     66,   "WATSCRE1",         "",     DEFAULT,       DEFAULT,     230,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,     67,   "WATSCRE1",         "",     DEFAULT,       DEFAULT,     210,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,    126,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     260,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,    128,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     260,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,    129,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     260,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,    131,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     260,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,    132,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     260,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,    137,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     260,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,    139,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     260,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,    157,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     360,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,    162,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     360,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,    173,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     360,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,    176,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     360,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,    182,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     360,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,    185,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     360,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,    189,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     260,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,    191,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     260,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,    192,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     260,  DEFAULT,   DEFAULT },
    {  heretic,       2,   5,    195,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     260,  DEFAULT,   DEFAULT },
    {  heretic,       2,   7,    105,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   7,    110,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   7,    111,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   7,    112,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   7,    113,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   7,    114,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   7,    115,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   7,    116,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   7,    117,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   7,    118,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   7,    119,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   7,    120,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       2,   7,    122,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       3,   4,     54,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     280,  DEFAULT,   DEFAULT },
    {  heretic,       3,   9,     87,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       4,   7,     50,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       4,   7,     95,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       4,   7,     96,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       4,   7,     99,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       4,   7,    104,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       4,   7,    105,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       4,   7,    125,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       4,   7,    157,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       4,   7,    187,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       4,   7,    225,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       4,   7,    306,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       4,   7,    307,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       4,   7,    338,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       4,   7,    340,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       4,   9,    380,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,      1,   "WATSCRS1",         "",     DEFAULT,       DEFAULT,     320,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,      2,   "WATSCRS1",         "",     DEFAULT,       DEFAULT,     320,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,      5,   "WATSCRS1",         "",     DEFAULT,       DEFAULT,     320,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,      6,   "WATSCRS1",         "",     DEFAULT,       DEFAULT,     320,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,      7,   "WATSCRS1",         "",     DEFAULT,       DEFAULT,     320,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,      8,   "WATSCRE1",         "",     DEFAULT,       DEFAULT,     220,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,      9,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     270,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     10,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     280,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     14,   "WATSCRE1",         "",     DEFAULT,       DEFAULT,     230,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     15,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     280,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     23,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     270,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     24,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     270,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     25,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     370,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     26,   "WATSCRE1",         "",     DEFAULT,       DEFAULT,     220,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     27,   "WATSCRE1",         "",     DEFAULT,       DEFAULT,     220,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     28,   "WATSCRE1",         "",     DEFAULT,       DEFAULT,     220,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     29,   "WATSCRE1",         "",     DEFAULT,       DEFAULT,     220,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     30,   "WATSCRE1",         "",     DEFAULT,       DEFAULT,     220,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     31,   "WATSCRE1",         "",     DEFAULT,       DEFAULT,     220,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     32,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     270,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     33,   "WATSCRE1",         "",     DEFAULT,       DEFAULT,     220,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     34,   "WATSCRS1",         "",     DEFAULT,       DEFAULT,     330,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     35,   "WATSCRE1",         "",     DEFAULT,       DEFAULT,     220,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     37,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     370,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     38,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     370,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     39,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     370,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     40,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     370,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     43,   "WATSCRS1",         "",     DEFAULT,       DEFAULT,     320,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     44,   "WATSCRE1",         "",     DEFAULT,       DEFAULT,     220,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     45,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     270,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     51,   "WATSCRS1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     52,   "WATSCRS1",         "",     DEFAULT,       DEFAULT,     320,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     53,   "WATSCRS1",         "",     DEFAULT,       DEFAULT,     320,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     54,   "WATSCRS1",         "",     DEFAULT,       DEFAULT,     320,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     55,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     370,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     56,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     270,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     57,   "WATSCRS1",         "",     DEFAULT,       DEFAULT,     320,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     60,   "WATSCRS1",         "",     DEFAULT,       DEFAULT,     340,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     61,   "WATSCRS1",         "",     DEFAULT,       DEFAULT,     320,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     63,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     370,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     64,   "WATSCRS1",         "",     DEFAULT,       DEFAULT,     320,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     65,   "WATSCRE1",         "",     DEFAULT,       DEFAULT,     220,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     66,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     280,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     68,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     280,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     69,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     270,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     70,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     370,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     71,   "WATSCRS1",         "",     DEFAULT,       DEFAULT,     320,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     73,   "WATSCRS1",         "",     DEFAULT,       DEFAULT,     340,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     74,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     270,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     75,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     270,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     76,   "WATSCRS1",         "",     DEFAULT,       DEFAULT,     330,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     77,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     280,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     78,   "WATSCRE1",         "",     DEFAULT,       DEFAULT,     240,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     79,   "WATSCRS1",         "",     DEFAULT,       DEFAULT,     330,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     80,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     370,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     86,   "WATSCRS1",         "",     DEFAULT,       DEFAULT,     320,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,     97,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     270,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,    111,   "WATSCRE1",         "",     DEFAULT,       DEFAULT,     220,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,    116,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     370,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,    117,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     270,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,    121,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     380,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,    122,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     380,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,    124,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     380,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,    125,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     380,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,    128,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     370,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,    130,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     360,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,    131,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     380,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,    132,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     280,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,    134,   "WATSCRN1",         "",     DEFAULT,       DEFAULT,     280,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,    135,   "WATSCRE1",         "",     DEFAULT,       DEFAULT,     230,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,    136,   "WATSCRE1",         "",     DEFAULT,       DEFAULT,     210,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,    137,   "WATSCRE1",         "",     DEFAULT,       DEFAULT,     210,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,    138,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     380,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,    139,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     380,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,    140,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     380,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,    141,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     380,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,    142,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     380,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,    143,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     380,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,    144,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     380,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,    145,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     380,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,    165,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     380,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,    166,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     380,  DEFAULT,   DEFAULT },
    {  heretic,       5,   2,    167,   "WATSCRW1",         "",     DEFAULT,       DEFAULT,     380,  DEFAULT,   DEFAULT },
    {  heretic,       5,   3,    176,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       5,   3,    210,           "",         "",          56,            56, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       5,   5,    192,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       5,   5,    196,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       5,   5,    197,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       5,   5,    219,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       5,   5,    268,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
    {  heretic,       5,   5,    272,    "SMLAVA1",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },


    {        0,       0,   0,      0,           "",         "",     DEFAULT,       DEFAULT, DEFAULT,  DEFAULT,   DEFAULT },
};

thingfix_t thingfix[] =
{
    // mission, episode, map, thing,  type,    oldx,    oldy,    newx,    newy,   angle, options
//  [JN] Nothing for now. An example:
//  {  heretic,       1,   6,    16,  3002,     800,    -704,     800,    -688, DEFAULT, DEFAULT },
    {        0,       0,   0,     0,     0, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT, DEFAULT }
};
