//
// Copyright(C) 2013-2018 Brad Harding
// Copyright(C) 2018 Julian Nechaevsky
//
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// DESCRIPTION:
//	Verious level-specific fixes.
//
//  Note: The idea and the code has beed taken from Doom Retro.
//  Many thanks to Brad Harding for approval of using his work! 
//


#include "p_fix.h"
#include "r_defs.h"


linefix_t linefix[] =
{
   // mission,    episode, map, linedef, side, toptexture, middletexture, bottomtexture,  offset, rowoffset, flags,                              special,                                    tag

    { doom,             1,   1,     160,    0, "",         "",            "NUKE24",      DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             1,   1,     161,    0, "",         "",            "NUKE24",      DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             1,   1,     162,    0, "",         "",            "NUKE24",      DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             1,   1,     163,    0, "",         "",            "NUKE24",      DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             1,   1,     164,    0, "",         "",            "NUKE24",      DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             1,   1,     165,    0, "",         "",            "NUKE24",      DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             1,   1,     166,    0, "",         "",            "NUKE24",      DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             1,   1,     167,    0, "",         "",            "NUKE24",      DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    
    { doom,             1,   2,     134,    1, "STARTAN2", "",            "",            DEFAULT,        69, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             1,   2,     281,    0, "",         "",            "",                -36,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             1,   2,     574,    1, "COMPTALL", "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             1,   2,     986,    0, "",         "",            "",                 64,         8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    
    { doom,             1,   3,     434,    0, "STONE",    "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    
    { doom,             1,   4,     321,    0, "",         "",            "STEP1",       DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             1,   4,     327,    0, "",         "",            "STEP1",       DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             1,   4,     338,    0, "",         "",            "STEP1",       DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             1,   4,     346,    0, "",         "",            "STEP1",       DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             1,   4,     693,    1, "BROWN96",  "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    
    { doom,             1,   5,      37,    0, "",         "",            "",                 -2,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             1,   5,      43,    0, "",         "",            "",                 -2,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    
    { doom,             1,   6,      30,    0, "",         "",            "",                  1,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             1,   6,      31,    0, "",         "",            "",                  2,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    
    { doom,             1,   7,     450,    1, "COMPTALL", "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             1,   7,     744,    1, "",         "",            "TEKWALL1",    DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             1,   7,     745,    1, "",         "",            "TEKWALL1",    DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             1,   7,     746,    1, "",         "",            "TEKWALL1",    DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             1,   7,     747,    1, "",         "",            "TEKWALL1",    DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    
    { doom,             2,   1,      48,    0, "",         "",            "",            DEFAULT,        -4, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   1,     174,    0, "",         "",            "",                 87,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   1,     182,    0, "",         "",            "",                 64,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   1,     239,    0, "",         "",            "",            DEFAULT,        64, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   1,     240,    0, "",         "",            "",            DEFAULT,        64, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   1,     242,    0, "",         "",            "",            DEFAULT,        64, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   1,     243,    0, "",         "",            "",            DEFAULT,        64, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   1,     244,    0, "",         "",            "",            DEFAULT,        64, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   1,     245,    0, "",         "",            "",            DEFAULT,        64, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   1,     246,    0, "",         "",            "",            DEFAULT,        64, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   1,     247,    0, "",         "",            "",            DEFAULT,        64, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   1,     250,    0, "",         "",            "",            DEFAULT,        64, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   1,     251,    0, "",         "",            "",            DEFAULT,        64, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   1,     252,    0, "",         "",            "",            DEFAULT,        64, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   1,     253,    0, "",         "",            "",            DEFAULT,        64, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   1,     254,    0, "",         "",            "",            DEFAULT,        64, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   1,     255,    0, "",         "",            "",            DEFAULT,        64, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   1,     256,    0, "",         "",            "",            DEFAULT,        64, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   1,     257,    0, "",         "",            "",            DEFAULT,        64, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   1,     323,    0, "",         "",            "",            DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   1,     324,    0, "",         "",            "",            DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    
    { doom,             2,   2,     412,    0, "",         "",            "",                 64,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   2,     722,    1, "",         "",            "",                 24,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   2,     760,    0, "",         "",            "GRAYBIG",     DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   2,     947,    0, "BROWN1",   "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   2,    1451,    0, "",         "",            "",                 88,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   2,    1491,    1, "ICKWALL2", "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   2,    1505,    0, "",         "",            "",            DEFAULT,        32, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   2,    1506,    0, "",         "",            "",            DEFAULT,        32, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   2,    1596,    1, "WOOD1",    "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },

    { doom,             2,   3,     267,    0, "",         "",            "",            DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   3,     268,    0, "",         "",            "",            DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   3,     270,    0, "",         "",            "",            DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   3,     271,    0, "",         "",            "",            DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   3,     478,    0, "",         "",            "",            DEFAULT,        32, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   3,     479,    0, "",         "",            "",            DEFAULT,        32, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   3,     480,    0, "",         "",            "",            DEFAULT,        32, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   3,     481,    0, "",         "",            "",            DEFAULT,        32, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   3,     518,    0, "",         "",            "",            DEFAULT,        32, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   3,     871,    0, "",         "",            "",            DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   3,     872,    0, "",         "",            "",            DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   3,     905,    1, "",         "MIDBRN1",     "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   3,     906,    1, "",         "MIDBRN1",     "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   3,     907,    1, "",         "MIDBRN1",     "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   3,     908,    1, "",         "MIDBRN1",     "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    
    { doom,             2,   4,     551,    1, "PIPE4",    "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   4,     865,    1, "",         "",            "STEP5",       DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   4,     955,    1, "",         "MIDGRATE",    "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   4,    1062,    0, "SLADWALL", "",            "",                 32,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   4,    1071,    0, "GRAYTALL", "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    
    { doom,             2,   5,     590,    0, "",         "",            "STEP1",       DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   5,     590,    1, "BROVINE",  "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   5,    1027,    1, "COMPSPAN", "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    
    { doom,             2,   6,     460,    0, "",         "",            "",                -14,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   6,     461,    0, "",         "",            "",                 -8,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   6,     462,    0, "",         "",            "",                -12,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   6,     463,    0, "",         "",            "",                -14,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   6,     463,    0, "",         "",            "",                 -9,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   6,     465,    0, "",         "",            "",                 52,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   6,     475,    0, "",         "",            "",                 10,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   6,     478,    0, "",         "",            "",                 12,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   6,     479,    0, "",         "",            "",                  6,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   6,     482,    0, "",         "",            "",                  8,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   6,     499,    0, "",         "",            "",                  8,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   6,     501,    0, "",         "",            "",                 10,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   6,     505,    0, "",         "",            "",                  6,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   6,     619,    0, "",         "",            "",            DEFAULT,   DEFAULT, (ML_DONTPEGTOP | ML_DONTPEGBOTTOM), DEFAULT,                                    DEFAULT },
    { doom,             2,   6,     639,    0, "EXITSIGN", "",            "",                 -8,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   6,     640,    0, "EXITSIGN", "",            "",                 -8,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   6,     747,    0, "",         "",            "",                 -2,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   6,     750,    0, "",         "",            "",                 -2,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   6,     757,    0, "",         "",            "",                 -1,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   6,     756,    0, "",         "",            "",                 -1,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   6,     758,    0, "",         "",            "",                 -1,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   6,    1000,    0, "",         "",            "",            DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   6,    1005,    0, "",         "",            "",            DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   6,    1011,    0, "",         "",            "",            DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   6,    1012,    0, "",         "",            "",            DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   6,    1091,    1, "STEP4",    "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    
    { doom,             2,   7,      24,    0, "",         "",            "",            DEFAULT,   DEFAULT, ML_DONTPEGBOTTOM,                   DEFAULT,                                    DEFAULT },
    { doom,             2,   7,      30,    0, "",         "",            "",            DEFAULT,   DEFAULT, ML_DONTPEGBOTTOM,                   DEFAULT,                                    DEFAULT },
    { doom,             2,   7,      38,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,      40,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,      42,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,      45,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,      48,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     197,    0, "",         "",            "",            DEFAULT,   DEFAULT, ML_DONTPEGBOTTOM,                   DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     205,    0, "",         "",            "",            DEFAULT,         0, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     209,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     216,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     225,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     230,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     235,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     285,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     315,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     345,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     346,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     347,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     349,    0, "",         "",            "",            DEFAULT,         1, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     355,    0, "",         "",            "",            DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     357,    0, "",         "",            "",            DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     359,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     428,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     467,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     468,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     469,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     470,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     484,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     485,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     486,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     491,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     492,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     493,    0, "",         "",            "",            DEFAULT,        56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     673,    0, "",         "",            "",            DEFAULT,        36, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     674,    0, "",         "",            "",            DEFAULT,        36, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     675,    0, "",         "",            "",            DEFAULT,        36, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     676,    0, "",         "",            "",            DEFAULT,        36, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     677,    0, "",         "",            "",            DEFAULT,        36, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     678,    0, "",         "",            "",            DEFAULT,        36, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     700,    0, "",         "",            "",                -56,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     701,    0, "",         "",            "",                -48,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     706,    0, "",         "",            "",            DEFAULT,   DEFAULT, ML_DONTPEGTOP,                      DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     735,    0, "",         "",            "",            DEFAULT,   DEFAULT, ML_DONTPEGTOP,                      DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     738,    0, "",         "",            "",            DEFAULT,   DEFAULT, ML_DONTPEGTOP,                      DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     741,    0, "",         "",            "",            DEFAULT,   DEFAULT, ML_DONTPEGTOP,                      DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     744,    0, "",         "",            "",            DEFAULT,   DEFAULT, ML_DONTPEGTOP,                      DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     904,    0, "",         "",            "",                 88,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,     962,    0, "",         "",            "",            DEFAULT,   DEFAULT, ML_DONTPEGTOP,                      DEFAULT,                                    DEFAULT },
    { doom,             2,   7,    1286,    0, "",         "",            "SHAWN2",      DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,    1362,    0, "",         "",            "",            DEFAULT,        40, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,    1363,    0, "",         "",            "",                 64,        40, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,    1364,    0, "",         "",            "",               -209,        40, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,    1365,    0, "",         "",            "",                -17,        40, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,    1366,    0, "",         "",            "",               -182,        40, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,    1367,    0, "",         "",            "",               -118,        40, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,    1368,    0, "",         "",            "",                -27,        40, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,    1369,    0, "",         "",            "",                -91,        40, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,    1418,    0, "",         "",            "",            DEFAULT,   DEFAULT, (ML_DONTPEGTOP | ML_DONTPEGBOTTOM), DEFAULT,                                    DEFAULT },
    { doom,             2,   7,    1645,    0, "",         "",            "",                 32,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   7,    1662,    0, "",         "",            "",                 32,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    
    { doom,             2,   9,     110,    1, "",         "MIDGRATE",    "",                 32,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   9,     115,    1, "",         "MIDGRATE",    "",                 32,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   9,     121,    1, "GSTONE1",  "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   9,     123,    1, "GSTONE1",  "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             2,   9,     140,    1, "GSTONE1",  "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    
    { doom,             3,   2,     146,    1, "",         "MIDVINE1",    "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   2,     433,    1, "",         "",            "ASHWALL",     DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   2,     434,    1, "",         "",            "ASHWALL",     DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   2,     435,    1, "",         "",            "ASHWALL",     DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   2,     436,    1, "",         "",            "ASHWALL",     DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   2,     452,    0, "",         "",            "",            DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   2,     454,    0, "",         "",            "",            DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    
    { doom,             3,   3,     790,    0, "",         "",            "",            DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   3,     791,    0, "",         "",            "",            DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   3,     793,    0, "",         "",            "",            DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   3,     797,    0, "",         "",            "",            DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   3,     854,    1, "",         "MIDGRATE",    "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   3,     855,    1, "",         "MIDGRATE",    "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   3,     994,    1, "SLADWALL", "MIDGRATE",    "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   3,     995,    1, "",         "MIDGRATE",    "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   3,     996,    1, "",         "MIDGRATE",    "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   3,    1055,    0, "",         "NUKE24",      "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   3,    1056,    0, "",         "NUKE24",      "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   3,    1057,    0, "",         "NUKE24",      "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    
    { doom,             3,   4,       3,    0, "",         "",            "",                  8,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,       4,    0, "",         "",            "",                  8,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,      16,    0, "",         "",            "",            DEFAULT,   DEFAULT, (ML_DONTPEGTOP | ML_DONTPEGBOTTOM), DEFAULT,                                    DEFAULT },
    { doom,             3,   4,      92,    0, "",         "",            "",            DEFAULT,   DEFAULT, (ML_DONTPEGTOP | ML_DONTPEGBOTTOM), DEFAULT,                                    DEFAULT },
    { doom,             3,   4,      93,    0, "",         "",            "",            DEFAULT,   DEFAULT, (ML_DONTPEGTOP | ML_DONTPEGBOTTOM), DEFAULT,                                    DEFAULT },
    { doom,             3,   4,      94,    0, "",         "",            "",            DEFAULT,   DEFAULT, (ML_DONTPEGTOP | ML_DONTPEGBOTTOM), DEFAULT,                                    DEFAULT },
    { doom,             3,   4,      95,    0, "",         "",            "",            DEFAULT,   DEFAULT, (ML_DONTPEGTOP | ML_DONTPEGBOTTOM), DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     185,    0, "",         "",            "",            DEFAULT,        72, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     186,    0, "",         "",            "",            DEFAULT,        72, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     187,    0, "",         "",            "",            DEFAULT,        72, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     236,    0, "",         "",            "",            DEFAULT,        72, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     237,    0, "",         "",            "",            DEFAULT,        72, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     238,    0, "",         "",            "",            DEFAULT,        72, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     239,    0, "",         "",            "",            DEFAULT,        72, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     240,    0, "",         "",            "",            DEFAULT,        72, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     241,    0, "",         "",            "",            DEFAULT,        72, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     242,    0, "",         "",            "",            DEFAULT,        72, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     243,    0, "",         "",            "",            DEFAULT,        72, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     244,    0, "",         "",            "",            DEFAULT,        72, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     470,    0, "BIGDOOR2", "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     657,    0, "",         "",            "",            DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     659,    0, "",         "",            "",                  0,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     660,    0, "",         "",            "",                  0,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     662,    0, "",         "",            "",            DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     667,    0, "",         "",            "",            DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     668,    0, "",         "",            "",            DEFAULT,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     674,    0, "",         "",            "",                  4,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     675,    0, "",         "",            "",                  4,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     773,    0, "",         "",            "",            DEFAULT,   DEFAULT, (ML_DONTPEGTOP | ML_DONTPEGBOTTOM), DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     774,    0, "",         "",            "",            DEFAULT,   DEFAULT, (ML_DONTPEGTOP | ML_DONTPEGBOTTOM), DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     776,    0, "",         "",            "",                -23,         8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     778,    0, "",         "",            "",                 23,         8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     781,    0, "",         "",            "",                -23,         8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     783,    0, "",         "",            "",                 11,         8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,     859,    0, "",         "",            "",            DEFAULT,   DEFAULT, ML_DONTPEGTOP,                      DEFAULT,                                    DEFAULT },
    { doom,             3,   4,    1070,    0, "",         "",            "",            DEFAULT,        72, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   4,    1071,    0, "",         "",            "",            DEFAULT,        72, DEFAULT,                            DEFAULT,                                    DEFAULT },
    
    { doom,             3,   5,     294,    0, "",         "",            "",            DEFAULT,   DEFAULT, ML_DONTPEGTOP,                      DEFAULT,                                    DEFAULT },
    { doom,             3,   5,     295,    0, "",         "",            "",            DEFAULT,   DEFAULT, ML_DONTPEGTOP,                      DEFAULT,                                    DEFAULT },
    { doom,             3,   5,     597,    0, "",         "",            "",            DEFAULT,   DEFAULT, ML_DONTPEGBOTTOM,                   DEFAULT,                                    DEFAULT },
    { doom,             3,   5,     598,    0, "",         "",            "",            DEFAULT,   DEFAULT, ML_DONTPEGBOTTOM,                   DEFAULT,                                    DEFAULT },
    { doom,             3,   5,    1056,    0, "",         "",            "",                  4,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   5,    1057,    0, "",         "",            "",                  4,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   5,    1329,    1, "",         "",            "GSTONE1",     DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   5,    1330,    1, "",         "",            "GSTONE1",     DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },

    { doom,             3,   6,     408,    1, "",         "BRNSMAL2",    "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   6,     410,    1, "",         "BRNSMAL2",    "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   6,     412,    1, "",         "BRNSMAL1",    "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   6,     414,    1, "",         "BRNSMAL2",    "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   6,     544,    0, "",         "",            "",            DEFAULT,        -9, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   6,     583,    0, "",         "",            "",            DEFAULT,        40, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   6,     662,    0, "",         "",            "",            DEFAULT,        24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    
    { doom,             3,   7,      71,    0, "",         "",            "",            DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,      72,    0, "",         "",            "",            DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,      73,    0, "",         "",            "",            DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,      74,    0, "",         "",            "",            DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,      75,    0, "",         "",            "",            DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,      76,    0, "",         "",            "",            DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,      77,    0, "",         "",            "",            DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,      78,    0, "",         "",            "",            DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     102,    0, "",         "",            "",            DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     221,    0, "",         "",            "GSTONE2",     DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     222,    0, "",         "",            "GSTONE2",     DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     223,    0, "",         "",            "GSTONE2",     DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     224,    0, "",         "",            "GSTONE2",     DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     225,    0, "",         "",            "GSTONE2",     DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     226,    0, "",         "",            "GSTONE2",     DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     227,    0, "",         "",            "GSTONE2",     DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     228,    0, "",         "",            "GSTONE2",     DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     229,    0, "",         "",            "GSTONE2",     DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     230,    0, "",         "",            "GSTONE2",     DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     231,    0, "",         "",            "GSTONE2",     DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     232,    0, "",         "",            "GSTONE2",     DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     233,    0, "",         "",            "GSTONE2",     DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     234,    0, "",         "",            "GSTONE2",     DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     235,    0, "",         "",            "GSTONE2",     DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     236,    0, "",         "",            "GSTONE2",     DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     237,    0, "",         "",            "GSTONE2",     DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     238,    0, "",         "",            "GSTONE2",     DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     312,    0, "",         "",            "",            DEFAULT,       -56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     314,    0, "",         "",            "",            DEFAULT,       -56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     317,    0, "",         "",            "",            DEFAULT,       -56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     319,    0, "",         "",            "",            DEFAULT,       -56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     377,    0, "",         "",            "",            DEFAULT,   DEFAULT, ML_DONTPEGTOP,                      DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     683,    0, "",         "",            "GSTONE2",     DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     684,    0, "",         "",            "GSTONE2",     DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     685,    0, "",         "",            "GSTONE2",     DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     686,    0, "",         "",            "GSTONE2",     DEFAULT,       -24, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     845,    0, "",         "",            "",            DEFAULT,       -32, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     846,    0, "",         "",            "",            DEFAULT,       -32, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     899,    0, "",         "",            "",            DEFAULT,       -32, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     901,    1, "",         "",            "STEP2",       DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     971,    1, "SP_HOT1",  "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     973,    0, "",         "",            "",            DEFAULT,        -7, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   7,     976,    0, "",         "",            "",            DEFAULT,        -7, DEFAULT,                            DEFAULT,                                    DEFAULT },
    
    { doom,             3,   9,      17,    0, "",         "",            "",                 96,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   9,      18,    0, "",         "",            "",                208,        -8, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   9,     102,    1, "",         "",            "STONE3",      DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   9,     285,    0, "",         "",            "",                 72,        11, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   9,     286,    0, "",         "",            "",                136,        11, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             3,   9,     287,    0, "",         "",            "",                200,        11, DEFAULT,                            DEFAULT,                                    DEFAULT },
    
    { doom,             4,   1,      58,    0, "",         "",            "",                 32,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   1,      80,    0, "",         "",            "",                 16,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   1,      81,    0, "",         "",            "",                 48,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   1,      83,    0, "",         "",            "",                 16,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   1,      84,    0, "",         "",            "",                 48,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   1,     124,    0, "",         "",            "",                  4,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   1,     126,    0, "",         "",            "",                  4,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   1,     193,    0, "",         "",            "",                 -8,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   1,     195,    0, "",         "",            "",                 -8,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   1,     454,    0, "",         "SUPPORT3",    "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   1,     456,    0, "",         "",            "",                  4,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   1,     458,    0, "",         "",            "",                  4,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   1,     461,    0, "EXITSIGN", "",            "",                 -8,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   1,     463,    0, "EXITSIGN", "",            "",                 -8,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   1,     466,    0, "",         "",            "",                 -4,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   1,     468,    0, "",         "",            "",                 -4,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   1,     470,    0, "GSTONE1",  "",            "",            DEFAULT,   DEFAULT, ML_DONTPEGTOP,                      DEFAULT,                                    DEFAULT },
    
    { doom,             4,   2,     165,    1, "WOOD5",    "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   2,     584,    0, "",         "",            "",            DEFAULT,        40, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   2,     585,    0, "",         "",            "",            DEFAULT,        40, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   2,     587,    0, "",         "",            "",            DEFAULT,        40, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   2,     588,    0, "",         "",            "",            DEFAULT,        40, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   2,     620,    0, "",         "",            "",                 16,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   2,     621,    0, "",         "",            "",                 48,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   2,     623,    0, "",         "",            "",                 48,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   2,     630,    0, "",         "",            "",                 16,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    
    { doom,             4,   4,      86,    0, "",         "",            "",                 -4,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   4,      87,    0, "",         "",            "",                  4,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   4,      88,    0, "",         "",            "",                 -4,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   4,      89,    0, "",         "",            "",                  4,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   4,      90,    0, "",         "",            "",                 -4,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   4,      91,    0, "",         "",            "",                  4,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   4,      92,    0, "",         "",            "",                 -4,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   4,      93,    0, "",         "",            "",                  4,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   4,      94,    0, "",         "",            "",                 -4,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   4,      95,    0, "",         "",            "",                  4,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   4,      96,    0, "",         "",            "",                 -4,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   4,      97,    0, "",         "",            "",                  4,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   4,     427,    1, "BROWNHUG", "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   4,     558,    1, "BROWNHUG", "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   4,     567,    0, "BROWNHUG", "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   4,     572,    0, "BROWNHUG", "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   4,     578,    0, "EXITSIGN", "",            "",                 -8,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   4,     580,    0, "EXITSIGN", "",            "",                 -8,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    
    { doom,             4,   5,      19,    1, "",         "",            "GSTONE",      DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   5,     109,    1, "GSTONE1",  "",            "",            DEFAULT,   DEFAULT, ML_DONTPEGTOP,                      DEFAULT,                                    DEFAULT },
    { doom,             4,   5,     777,    0, "",         "BROVINE2",    "",                 39,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   5,     779,    0, "",         "BROVINE2",    "",                -64,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   5,     974,    0, "",         "",            "",            DEFAULT,       -56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   5,     975,    0, "",         "",            "",            DEFAULT,       -56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   5,     976,    0, "",         "",            "",            DEFAULT,       -56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   5,     977,    0, "",         "",            "",            DEFAULT,       -56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   5,     978,    0, "",         "",            "",            DEFAULT,       -56, DEFAULT,                            DEFAULT,                                    DEFAULT },
    
    { doom,             4,   6,     475,    1, "MARBLE1",  "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   6,     476,    1, "MARBLE1",  "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   6,     479,    1, "MARBLE1",  "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   6,     480,    1, "MARBLE1",  "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   6,     481,    1, "MARBLE1",  "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   6,     482,    1, "MARBLE1",  "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   6,     848,    0, "",         "",            "",                  8,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   6,     850,    0, "",         "",            "",                  8,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   6,     887,    0, "",         "",            "",                  8,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   6,     889,    0, "",         "",            "",                  8,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   6,    1316,    0, "",         "",            "",                 29,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   6,    1317,    0, "",         "",            "",                 63,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    
    { doom,             4,   7,     276,    0, "",         "",            "",            DEFAULT,       128, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   7,     325,    1, "",         "BRNBIGR",     "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   7,     326,    1, "",         "BRNBIGC",     "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   7,     327,    1, "",         "BRNBIGL",     "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   7,     451,    1, "",         "BRNBIGR",     "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   7,     452,    1, "",         "BRNBIGC",     "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   7,     453,    1, "",         "BRNBIGL",     "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   7,     475,    0, "",         "",            "",            DEFAULT,       128, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   7,     477,    0, "",         "",            "NUKEDGE1",    DEFAULT,       -12, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   7,     478,    0, "",         "",            "NUKEDGE1",    DEFAULT,       -12, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   7,     989,    0, "",         "NUKEDGE1",    "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   7,     991,    0, "",         "NUKEDGE1",    "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    
    { doom,             4,   8,      69,    0, "",         "",            "",                 26,       -64, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   8,     418,    0, "",         "SP_HOT1",     "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   8,     419,    0, "",         "SP_HOT1",     "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   8,     420,    0, "",         "SP_HOT1",     "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   8,     425,    0, "",         "SP_HOT1",     "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   8,     513,    0, "",         "",            "",            DEFAULT,   DEFAULT, ML_DONTPEGTOP,                      DEFAULT,                                    DEFAULT },
    { doom,             4,   8,     570,    0, "",         "",            "",            DEFAULT,   DEFAULT, ML_DONTPEGTOP,                      DEFAULT,                                    DEFAULT },
    { doom,             4,   8,     576,    0, "",         "",            "",            DEFAULT,   DEFAULT, ML_DONTPEGTOP,                      DEFAULT,                                    DEFAULT },
    { doom,             4,   8,     579,    0, "",         "",            "",            DEFAULT,   DEFAULT, ML_DONTPEGTOP,                      DEFAULT,                                    DEFAULT },
    { doom,             4,   8,     596,    0, "",         "",            "",            DEFAULT,   DEFAULT, ML_DONTPEGTOP,                      DEFAULT,                                    DEFAULT },
    { doom,             4,   8,     604,    0, "",         "",            "",            DEFAULT,   DEFAULT, ML_DONTPEGTOP,                      DEFAULT,                                    DEFAULT },
    
    { doom,             4,   9,     343,    0, "",         "METAL",       "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   9,     345,    0, "",         "METAL",       "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   9,    1175,    0, "",         "",            "CRATINY",     DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   9,    1176,    0, "",         "",            "CRATINY",     DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   9,    1195,    0, "",         "",            "",                 16,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   9,    1583,    0, "",         "",            "",            DEFAULT,      -120, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   9,    1584,    0, "",         "",            "",                 64,      -120, DEFAULT,                            DEFAULT,                                    DEFAULT },
    { doom,             4,   9,    1585,    0, "",         "",            "",            DEFAULT,      -120, DEFAULT,                            DEFAULT,                                    DEFAULT },
   
    
    { -1,               0,   0,       0,    0, "",         "",            "",            DEFAULT,   DEFAULT, DEFAULT,                            DEFAULT,                                    DEFAULT }
};

sectorfix_t sectorfix[] =
{
   // mission,    episode, map, sector, floorpic, ceilingpic, floorheight, ceilingheight, special,                            oldtag,  newtag

    { doom,             1,   1,     67, "",       "FLAT1",    DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },
    { doom,             1,   1,     71, "",       "FLAT1",    DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },

    { doom,             1,   3,      1, "",       "FLAT1",    DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },
    { doom,             1,   3,      6, "",       "FLAT1",    DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },
    { doom,             1,   3,     42, "",       "FLAT1",    DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },

    { doom,             1,   4,     56, "",       "FLAT1",    DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },

    { doom,             1,   5,    114, "",       "FLAT1",    DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },

    { doom,             1,   6,     32, "",       "FLAT1",    DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },

    { doom,             1,   7,    109, "",       "FLAT1",    DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },

    { doom,             1,   9,     44, "",       "FLAT1",    DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },
    { doom,             1,   9,     53, "",       "FLAT1",    DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },

    { doom,             2,   2,      8, "",       "FLAT1",    DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },

    { doom,             2,   3,    111, "",       "FLAT1",    DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },
    { doom,             2,   3,    112, "",       "FLAT1",    DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },

    { doom,             2,   4,    173, "BLOOD3", "FLAT1",    DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },
    { doom,             2,   4,    177, "BLOOD3", "FLAT1",    DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },

    { doom,             2,   5,    114, "",       "FLAT1",    DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },
    { doom,             2,   5,    119, "",       "FLAT1",    DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },
    
    { doom,             2,   6,    161, "",       "FLAT1",    DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },
    
    { doom,             2,   7,    251, "CRATOP2","",         DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },
    { doom,             2,   7,     57, "",       "FLAT1",    DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },
    
    { doom,             3,   3,    172, "",       "FLAT1",    DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },
    
    { doom,             3,   5,    150, "",       "FLAT1",    DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },
    
    { doom,             3,   6,     34, "",       "",         DEFAULT,     96,            DEFAULT,                            DEFAULT, DEFAULT },
    { doom,             3,   6,     89, "",       "",         DEFAULT,     96,            DEFAULT,                            DEFAULT, DEFAULT },
    
    { doom,             4,   1,     64, "",       "FLAT1",    DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },
    
    { doom,             4,   4,     62, "",       "FLAT1",    DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },
    
    { doom,             4,   5,    134, "FLAT1",  "",         DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },


    { -1,               0,   0,      0, "",       "",         DEFAULT,     DEFAULT,       DEFAULT,                            DEFAULT, DEFAULT },
};

